name: Release
on:
  push:
    branches:
    - master

jobs:
  tagpr:
    permissions:
      actions: write
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.run-tagpr.outputs.tag }}
    steps:
    - uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5 # v3.5.3
    - id: run-tagpr
      uses: Songmu/tagpr@43d52e123cf8d55db9d602601f115f530588e2f8 # v1.1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # The following codes are borrowed from https://github.com/ruby/vscode-rdbg/blob/master/.github/workflows/release.yml.
  publish:
    needs: tagpr
    if: needs.tagpr.outputs.tag != ''
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
    - name: Publish
      run: |
        npm install
        npm install --global @vscode/vsce
        vsce publish
      env:
        # To help protect secrets, we set VSCE_PAT as an environemnt variables.
        # https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
